---
  - name: started php-fpm
    become: yes
    service: 
      name: php-fpm 
      state: started
        
  - name: restart php-fpm
    become: yes
    service: 
      name: php-fpm 
      state: restarted